version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro               # Fichier de configuration Nginx personnalisé
      - ./nginx/certs:/etc/nginx/certs                            # Certificats TLS (Let's Encrypt)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/html:/usr/share/nginx/html                        # Page HTML statique (optionnel, ex: page maintenance)
      - client-dist:/usr/share/nginx/html/lapm                   # Volume monté contenant les fichiers buildés du frontend
    depends_on:
      - client
      - server

  db:
    image: mariadb:11
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    # Exposition du port vers les services internes de docker
    expose:
      - "3306"  # seulement accessible entre services Docker (sécurité)
    # Exposition de la DB vers l'extérieur en dehors de Docker
    ports:
      - "3306:3306"  # DB accessible depuis l'extérieur le temps du dev

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args: # Arguments pour le build qui remplace "environment". Necessaire pour vite ! A configurer également dans le Dockerfile
        - VITE_NODE_ENV=production
        - VITE_DOMAIN_CLIENT=${VITE_DOMAIN_CLIENT}
        - VITE_DOMAIN_API_SERVER=${VITE_DOMAIN_API_SERVER}
    env_file: .env
    restart: always
    volumes:
      - client-dist:/app/dist  # Rend disponible le build Vite pour Nginx
    command: [ "sleep", "infinity" ]

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - VITE_DOMAIN_CLIENT=${VITE_DOMAIN_CLIENT}
      - VITE_DOMAIN_API_SERVER=${VITE_DOMAIN_API_SERVER}

      - VITE_PORT_API_SERVER=${VITE_PORT_API_SERVER}

      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

      - MAIL_SERVER_ADMIN=${MAIL_SERVER_ADMIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      - SECRET_KEY_TOKEN_CLIENT=${SECRET_KEY_TOKEN_CLIENT}
      - SECRET_KEY_TOKEN_API_SERVER=${SECRET_KEY_TOKEN_API_SERVER}
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads # Dossier pour les fichiers uploadés

volumes:
  db_data:
  client-dist:
