import ImagesControllerDataType from "../../types/ImagesControllerData.type";

const data_Album_Paysage = [
    "lapm-photographie-professionnelle-depart-ou-arrivee-tage-paysage-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-flamands-camargue-dos-a-dos-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-flamands-camargue-mimetisme-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-brume-chemin-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-brume-matinale-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-camargue-envols-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-camargue-sunset-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-cap-breton-bunkers-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-chateau-roche-posay-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-flamand-camargue-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-heure-bleue-meze-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-jetee-cap-breton-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-lac-salagou-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-remparts-aigues-mortes-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-immensité-sable-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-salins-aigues-mortes-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-sunset-flamands-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-printemps-nature-coquelicot-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-profesionnelle-camargue-chevaux-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-mont-saint-baudille-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-moselle-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-neige-arbres-aigoual-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-neige-mont-aigoual-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-paysage-penichel-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-agde-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-etang-de-thau-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-lever-de-soleil-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-montagne-devoluy-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-neige-arbres-aigoual-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-neige-mont-aigoual-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-peniche-moselle-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-remparts-aigues-mortes-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-salins-aigues-mortes-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-paysage-vignes-salagou-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-route-moureze-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-mobilier-urbain-gare-lisbonne-balance-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-gare-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-montpellier-street-cap-breton-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-urbain-escalier-rome-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-voie-lactée-aigoual-observatoire-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-paysage-goudet-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-paysage-urbain-arbre-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-street-la-sieste-cassis-studio-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-street-urbain-luma-arles-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-pro-paysage-avy-barrage-grabels-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-pro-paysage-tarn-foins-coupes-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-montpellier-urbaine-louvre-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-pro-architecture-nuit-noir-et-blanc-arc-de-triumph-l-atelier-photo-montpellier.jpg",
    "lapm-photograpie-professionnelle-urbaine-lisbonne-collinesl-atelier-photo-montpellier.jpg",
];

const data_Album_Street = [
    "lapm-photographie-professionnelle-photo-street-a-table-photo-rue-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-rue-peniche-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-service-compris-photo-rue-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-vendeur-lunettes-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-restaurant-street-photo-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-photo-street-boulangerie-l-attente-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-aeroport-l-attente-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-canal-photo-rue-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-dame-agee-photo-rue-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-photo-street-tenue-camouflage-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-table-photo-rue-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-montpellier-concert-contrebassiste-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-montpellier-street-gay-pride-montpellier-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-festival-bresilien-polygone-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-festival-etang-de-thau-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-gare-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-homme-ecusson-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-street-homme-festival-bresilien-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnelle-gay-pride-montpellier-char-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnelle-street-cap-breton-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-jeune-femme-street-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-pro-street-octobre-rose-toutes-a-moto-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-pro-street-port-mariane-reflets-l-atelier-photo-montpellier.jpg",
];

const data_Album_Urbaine = [
    "lapm-photographie-professionnelle-urbain-architecture-faux-semblant-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-architecture-photo-centre-pompidou-metz-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-architecture-photo-passerelle-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-boulangerie-lacoste-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-colline-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-embleme-paris-tour-eiffel-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-escalator-gare-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-grande-librairie-prendre-son-envol-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-immeuble-escalier-architecture-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-jardin-tuilerie-face-a-face-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-lisbonne-street-art-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-metro-antre-urbain-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-mobilier-urbain-sanisette-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-montgolfieres-photo-noir-blanc-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-montpellier-paysage-variation-reflet-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-montpellier-rues-de-nuit-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-palce-vendome-paris-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbain-paysage-urbain-nuit-montreal-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-grande-librairie-banker-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-hublot-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-urbain-volet-vert-l-atelier-photo-montpellier.jpg",
    "lapm-photo-pro-architecture-ciel-l-atelier-photo-montpellier.jpg",
    "lapm-photo-pro-architecture-matt-tage-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photo-pro-architecture-montpellier-l-atelier-photo-montpellier.jpg",
    "lapm-photo-pro-architecture-port-mariane-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-arceaux-acqueduc-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-bougainvilliers-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-cycliste-canaux-amsterdam-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-facade-jaune-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-lampadaires-lisbonne-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-paysage-acqueduc-quartier-arceaux-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-paysage-urbain-amsterdam-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-paysage-urbain-marseille-immeuble-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-urbain-arbre-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-urbain-architect-musee-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-urbain-architecture-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-vers-le-sacre-coeur-paris-l-atelier-photo-montpelliere.jpg",
    "lapm-photographe-professionel-mobilier-urbain-gare-lisbonne-balance-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionel-urbain-escalier-rome-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-paysage-urbain-arbre-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-street-urbain-luma-arles-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-pro-architecture-nuit-noir-et-blanc-arc-de-triumph-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-urbaine-louvre-l-atelier-photo-montpellier.jpg",
    "lapm-photograpie-professionnelle-urbaine-lisbonne-collines-l-atelier-photo-montpellier.jpg",
];

const data_Album_Pro_Perso = [
    "lapm-photographie-professionnelle-portrait-duo-generation-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-duo-mere-fils-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-duo-pere-fils-clair-obscur-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-duo-western-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-feelgood-solo-femme-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-feelgood-solo-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-feelgood-solo-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-femme-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-femme-rock-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-femme-rock-flash-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-femme-rock-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-flash-couple-ages-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-flash-couple-domicile-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-flash-duo-cox-boy-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-flash-grand-pere-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-flash-lifestyle-cowboy-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-jeune-homme-fellgood-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-jeune-homme-life-style-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-lifestyle-exterieur-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-lifestyle-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-lifesytle-femme-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-serie-annee-vingt-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-serie-peaky-blinders-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-femme-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-femme-soleil-rasant-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-jeune-homme-reflet-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-couple-duo-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-couple-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-couple-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-duo-couleur-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-duo-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-homme-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-nb-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-nb-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-solo-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-studio-type-harcourt-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-coiffure-femme-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-hugo-facon-harcourt-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-marie-t-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-mauricette-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-noelle-v1-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-noelle-v2-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-femme-melancolique-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-femme-naturelle-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-fine-art-jj-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-homme-balcon-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-homme-costume-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-homme-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-homme-veste-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnelle-portrait-duo-exterieur-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-corporate-chercheuse-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-duo-flash-studio-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-duo-jeune-couple-studio-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-grossesse-neuf-mois-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-a-montpellier-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-couple-engagement-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-discours-aux-maries-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-parc-fontaine-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-parc-ideal-nimes-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-signature-maries-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-sun-glass-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-nouveau-ne-dans-berceau-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-nouveau-ne-famille-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-solo-en-jardin-lifestyle-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-solo-exterieur-domicile-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-solo-homme-lifestyle-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-solo-homme-montpellier-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-corporate-agence-immo-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-corporate-assistante-direction-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-hobby-peaky-blinders-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-mariage-photo-exterieur-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-mariage-tour-magne-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-nouveau-ne-pere-fils-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-homme-exterieur-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-jeune-femme-lumiere-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-jeune-fille-grabels-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnel-portrait-duo-couple-studio-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnelle-portrait-duo-pere-fils-lifestyle-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-a-villeneuve-les-maguelones-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-duo-couple-montpellier-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-duo-flash-studio-detente-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-duo-tandem-exterieur-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-grossesse-premieres-images-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-mariage-florian-et-elsa-enlace-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-mariage-mariage-photo-exterieur-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-mariage-maries-en-plein-soleil-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-nouveau-ne-berceau-et-tableau-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-clair-obscur-homme-studio-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-solo-parc-de-fontcolombe-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-corporate-bureau-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-corporate-cv-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-mariage-shooting-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnel-portrait-solo-mother-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-famille-fratrie-l-atelier-photo-montpellier.jpg",
    "lapm-photo-professionnel-portrait-famille-mamies-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-mariage-mariage-pride-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-corporate-commerciale-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-corporate-cv-flash-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-duo-couple-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-duo-pere-fils-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-famille-mere-fils-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-hobbie-moto-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-dame-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-duo-studio-couple-l-atelier-photo-montpellier.jpg",
    "lapm-photographie-professionnelle-portrait-solo-femme-a-la-cigarette-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-mariage-maryins-canisses-l-atelier-photo-montpellier.jpg",
    "lapm-photographe-professionnel-portrait-duo-mere-fils-l-atelier-photo-montpellier.jpg",
];

type ListeAlbumType = {
    Album_Paysage: ImagesControllerDataType[];
    Album_Rue_Street: ImagesControllerDataType[];
    Album_Urbaine: ImagesControllerDataType[];
    Album_Pro_Perso: ImagesControllerDataType[];
};

function generateAltFromFilename(filename: string): string {
  return filename
    .replace(/\.[^/.]+$/, '')            // Supprime l'extension (.jpg, .webp...)
    .replace(/[-_]/g, ' ')               // Remplace - et _ par des espaces
    .replace(/\s+/g, ' ')                // Supprime les doubles espaces
    .trim()
    .replace(/^\w/, (c) => c.toUpperCase()); // Majuscule en début
}

function GenerateTableImg(nbImg: number, basePath: string, allFileNames: string[]
): ImagesControllerDataType[] {
  const shuffled = [...allFileNames].sort(() => 0.5 - Math.random());
  const selected = shuffled.slice(0, nbImg);

  return selected.map((filename) => ({
    src: `${basePath}${filename}`,
    alt: generateAltFromFilename(filename),
  }));
}

const Album_Paysage = GenerateTableImg(15, "/images/image-portfolio/album-paysage/", data_Album_Paysage);
const Album_Rue_Street = GenerateTableImg(10, "/images/image-portfolio/album-rue-street/", data_Album_Street);
const Album_Urbaine = GenerateTableImg(15, "/images/image-portfolio/album-urbaine/", data_Album_Urbaine);
const Album_Pro_Perso = GenerateTableImg(25, "/images/image-portfolio/album-pro-perso/", data_Album_Pro_Perso);

const ImagesPortraitPortfolioControllerData: ListeAlbumType = {
    /* Portrait de particuliers et professionnels */
    Album_Paysage,
    Album_Rue_Street,
    Album_Urbaine,
    Album_Pro_Perso,
};

export default ImagesPortraitPortfolioControllerData;
