import ListDataRouter from "../../../router/router";
import CardPrestationType from "../../../types/CardPrestation.type";

function DataCardPrestation() {
    const tab: CardPrestationType[] = [
        {
            reactKey: 1,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "After day / trash the dress",
            description: "Prolongez la magie après le mariage.",
            image: "/images/image-prestation-card/canette.jpg",
        },
        {
            reactKey: 2,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Cérémonie laïque / religieuse",
            description: "Les moments forts de votre cérémonie.",
            image: "/images/image-prestation-card/mariage.jpg",
        },
        {
            reactKey: 3,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Enterrement de vie jeune fille",
            description: "Immortalisez ce moment unique entre proches.",
            image: "/images/image-prestation-card/evjf.jpg",
        },
        {
            reactKey: 4,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Enterrement de vie garçon",
            description: "Spéciale gueule de bois !",
            image: "/images/image-prestation-card/evg.jpg",
        },
        {
            reactKey: 5,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "EVJF / EVG",
            description: "Enterrez votre vie de célibataire.",
            image: "/images/image-prestation-card/soleil.jpg",
        },
        {
            reactKey: 6,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Maternité en images",
            description: "Des souvenirs tendres de cette étape.",
            image: "/images/image-prestation-card/grossesse.jpg",
        },
        {
            reactKey: 7,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Photo CV",
            description: "Donnez une première impression percutante.",
            image: "/images/image-prestation-card/cv.jpg",
        },
        {
            reactKey: 8,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Photo de profil",
            description: "Affirmez votre image avec un portrait qui vous ressemble.",
            image: "/images/image-prestation-card/reseau.jpg",
        },
        {
            reactKey: 9,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Photo Facebook",
            description: "Une photo naturelle et expressive pour votre profil.",
            image: "/images/image-prestation-card/solo.jpg",
        },
        {
            reactKey: 10,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Photo Instagram",
            description: "Un portrait stylisé pour embellir votre feed.",
            image: "/images/image-prestation-card/insta.jpg",
        },
        {
            reactKey: 11,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Photo Linkedin",
            description: "Un portrait qui inspire confiance.",
            image: "/images/image-prestation-card/linkedin.jpg",
        },
        {
            reactKey: 12,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Photo réseaux sociaux",
            description: "Un cliché soigné pour vous démarquer en ligne.",
            image: "/images/image-prestation-card/social.jpg",
        },
        {
            reactKey: 13,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Photo site internet",
            description: "Une image cohérente pour votre communication digitale.",
            image: "/images/image-prestation-card/internet.jpg",
        },
        {
            reactKey: 14,
            path: ListDataRouter[15].path,
            id: "tarifs-portrait-duo",
            title: "Portrait amis",
            description: "Des souvenirs complices à partager.",
            image: "/images/image-prestation-card/amis.jpg",
        },
        {
            reactKey: 15,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait animaux",
            description: "Mettez en lumière votre lien unique avec votre compagnon.",
            image: "/images/image-prestation-card/animaux.jpg",
        },
        {
            reactKey: 16,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait anniversaire",
            description: "Une séance fun pour marquer le moment.",
            image: "/images/image-prestation-card/anniversaire.jpg",
        },
        {
            reactKey: 17,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait artisan/créateur",
            description: "Valorisez votre savoir-faire en images.",
            image: "/images/image-prestation-card/artisant.jpg",
        },
        {
            reactKey: 18,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait artistique",
            description: "Créez un portrait unique, à votre image.",
            image: "/images/image-prestation-card/artiste.jpg",
        },
        {
            reactKey: 19,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Portrait bébé",
            description: "Immortalisez les premiers jours de bébé.",
            image: "/images/image-prestation-card/bebe.jpg",
        },
        {
            reactKey: 20,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait chat",
            description: "Des clichés doux et expressifs de votre félin adoré.",
            image: "/images/image-prestation-card/chat.jpg",
        },
        {
            reactKey: 21,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait cheval",
            description: "Célébrez la beauté et la force de votre monture.",
            image: "/images/image-prestation-card/cheval.jpg",
        },
        {
            reactKey: 22,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait chiens",
            description: "Un shooting complice pour votre fidèle ami.",
            image: "/images/image-prestation-card/chien.jpg",
        },
        {
            reactKey: 23,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Portrait corporate",
            description: "Mettez en avant votre image professionnelle.",
            image: "/images/image-prestation-card/corporate.jpg",
        },
        {
            reactKey: 24,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait cosplay",
            description: "Mettez en lumière vos personnages préférés.",
            image: "/images/image-prestation-card/cosplay.jpg",
        },
        {
            reactKey: 25,
            path: ListDataRouter[15].path,
            id: "tarifs-portrait-duo",
            title: "Portrait couple lifestyle",
            description: "Un moment tendre dans un lieu qui vous ressemble.",
            image: "/images/image-prestation-card/couple.jpg",
        },
        {
            reactKey: 26,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait hobby",
            description: "Un shooting sur-mesure pour votre univers.",
            image: "/images/image-prestation-card/createur.jpg",
        },
        {
            reactKey: 27,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait cyclisme / VTT",
            description: "Une séance pleine d’énergie et de liberté.",
            image: "/images/image-prestation-card/vtc.jpg",
        },
        {
            reactKey: 28,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Portrait d’équipe",
            description: "Montrez l’esprit de votre entreprise.",
            image: "/images/image-prestation-card/corporate-equipe.jpg",
        },
        {
            reactKey: 29,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait danseur/danseuse",
            description: "Sublimez le mouvement et l’émotion.",
            image: "/images/image-prestation-card/danse.jpg",
        },
        {
            reactKey: 30,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait de famille",
            description: "Des souvenirs à transmettre.",
            image: "/images/image-prestation-card/famille.jpg",
        },
        {
            reactKey: 31,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait de groupe",
            description: "Un shooting complice entre amis.",
            image: "/images/image-prestation-card/mamie.jpg",
        },
        {
            reactKey: 32,
            path: ListDataRouter[15].path,
            id: "tarifs-portrait-duo",
            title: "Portrait duo créatif",
            description: "Un shooting original pour raconter votre histoire à deux.",
            image: "/images/image-prestation-card/creatif.jpg",
        },
        {
            reactKey: 33,
            path: ListDataRouter[15].path,
            id: "tarifs-portrait-duo",
            title: "Portrait en duo",
            description: "Célébrez votre complicité en images.",
            image: "/images/image-prestation-card/duo.jpg",
        },
        {
            reactKey: 34,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait enfants",
            description: "Des instants précieux en famille.",
            image: "/images/image-prestation-card/enfant.jpg",
        },
        {
            reactKey: 35,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Portrait entrepreneur",
            description: "Valorisez votre marque personnelle.",
            image: "/images/image-prestation-card/entrepreneur.jpg",
        },
        {
            reactKey: 36,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait équin",
            description: "Immortalisez votre passion pour l’univers équestre.",
            image: "/images/image-prestation-card/equin.jpg",
        },
        {
            reactKey: 37,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait équitation",
            description: "Sublimez votre complicité avec le cheval.",
            image: "/images/image-prestation-card/cheval.jpg",
        },
        {
            reactKey: 38,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Portrait feel good",
            description: "Une séance pour se reconnecter à soi.",
            image: "/images/image-prestation-card/feel-good.jpg",
        },
        {
            reactKey: 39,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Portrait femme enceinte",
            description: "Une séance en douceur et en lumière.",
            image: "/images/image-prestation-card/ventre.jpg",
        },
        {
            reactKey: 40,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait générationnel",
            description: "Célébrez les liens entre les générations.",
            image: "/images/image-prestation-card/generationnel.jpg",
        },
        {
            reactKey: 41,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Portrait grossesse",
            description: "Sublimez ce moment unique de votre vie.",
            image: "/images/image-prestation-card/grossesse.jpg",
        },
        {
            reactKey: 43,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Portrait individuel",
            description: "Un moment pour vous, en toute authenticité.",
            image: "/images/image-prestation-card/individuel.jpg",
        },
        {
            reactKey: 44,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Portrait intergénérationnel",
            description: "Célébrez les liens entre les générations.",
            image: "/images/image-prestation-card/intergenerationnel.jpg",
        },
        {
            reactKey: 45,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Portrait invités",
            description: "Des souvenirs authentiques de votre mariage.",
            image: "/images/image-prestation-card/invite.jpg",
        },
        {
            reactKey: 46,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait moto",
            description: "Associez style et puissance dans une séance sur-mesure.",
            image: "/images/image-prestation-card/moto.jpg",
        },
        {
            reactKey: 47,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Portrait nouveau-né",
            description: "Capturez les tout premiers instants de bébé.",
            image: "/images/image-prestation-card/baby.jpg",
        },
        {
            reactKey: 48,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait passion",
            description: "Mettez en scène votre passion.",
            image: "/images/image-prestation-card/hobbie.jpg",
        },
        {
            reactKey: 49,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Portrait pour soi",
            description: "Un regard neuf sur vous-même.",
            image: "/images/image-prestation-card/soi.jpg",
        },
        {
            reactKey: 51,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait sport",
            description: "Capturez l’intensité de votre pratique.",
            image: "/images/image-prestation-card/sport.jpg",
        },
        {
            reactKey: 52,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait sportif",
            description: "Célébrez votre discipline en image.",
            image: "/images/image-prestation-card/sportif.jpg",
        },
        {
            reactKey: 54,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Portrait voiture",
            description: "Sublimez votre passion mécanique à travers des images fortes.",
            image: "/images/image-prestation-card/voiture.jpg",
        },
        {
            reactKey: 55,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Préparatifs mariage",
            description: "Immortalisez les instants avant le \"oui\".",
            image: "/images/image-prestation-card/preparatif.jpg",
        },
        {
            reactKey: 56,
            path: ListDataRouter[11].path,
            id: "tarifs-portrait-corporate",
            title: "Reportage en entreprise",
            description: "Mettez en valeur votre univers professionnel.",
            image: "/images/image-prestation-card/corporate-equipe.jpg",
        },
        {
            reactKey: 57,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Reportage mariage",
            description: "Racontez en images l’histoire de votre grand jour.",
            image: "/images/image-prestation-card/reportage.jpg",
        },
        {
            reactKey: 58,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Séance engagement",
            description: "Une séance avant le jour J pour se découvrir en photo.",
            image: "/images/image-prestation-card/engagement.jpg",
        },
        {
            reactKey: 59,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Séance naissance",
            description: "Des souvenirs précieux à chérir.",
            image: "/images/image-prestation-card/naissance.jpg",
        },
        {
            reactKey: 61,
            path: ListDataRouter[15].path,
            id: "tarifs-portrait-duo",
            title: "Shooting couple",
            description: "Immortalisez votre histoire d’amour.",
            image: "/images/image-prestation-card/love.jpg",
        },
        {
            reactKey: 62,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Shooting couple mariage",
            description: "Capturez l’émotion et la complicité des mariés.",
            image: "/images/image-prestation-card/maria.jpg",
        },
        {
            reactKey: 64,
            path: ListDataRouter[18].path,
            id: "tarifs-portrait-grossesse",
            title: "Shooting future maman",
            description: "Célébrez la magie de l’attente.",
            image: "/images/image-prestation-card/terme.jpg",
        },
        {
            reactKey: 66,
            path: ListDataRouter[19].path,
            id: "tarifs-portrait-hobby",
            title: "Shooting musicien/musicienne",
            description: "Des images qui vibrent au rythme de votre art.",
            image: "/images/image-prestation-card/musicien.jpg",
        },
        {
            reactKey: 67,
            path: ListDataRouter[14].path,
            id: "tarifs-portrait-solo",
            title: "Shooting solo",
            description: "Exprimez votre personnalité en images.",
            image: "/images/image-prestation-card/cigarette.jpg",
        },
        {
            reactKey: 68,
            path: ListDataRouter[16].path,
            id: "tarifs-portrait-famille",
            title: "Shooting tribu",
            description: "Une séance fun et décontractée.",
            image: "/images/image-prestation-card/tribu.jpg",
        },
        {
            reactKey: 69,
            path: ListDataRouter[13].path,
            id: "tarifs-portrait-mariage",
            title: "Mariage Pride",
            description: "Célébrez l'amour en arc-en-ciel.",
            image: "/images/image-prestation-card/pride.jpg",
        },
    ]
    return tab;
}


export default DataCardPrestation;
